Bump version to current in getting started pages
jshmrtn/crontab pull request #75
Opened 2020-10-21 01:37 UTC by GrantJamesPowell

2020-10-21 07:41 UTC, maennchen commented
@GrantJamesPowell Thanks for the PR!

2020-10-21 07:42 UTC, maennchen requested changes
I think we should loosen the recommended requirements a bit at the same time.

2020-10-21 07:42 UTC, maennchen commented on README.md
> +  [{:crontab, "~> 1.1.10"}]
```suggestion
  [{:crontab, "~> 1.1"}]
```

2020-10-21 07:42 UTC, maennchen commented on pages/Getting Started.md
> +      [{:crontab, "~> 1.1.10"}]
```suggestion
      [{:crontab, "~> 1.1"}]
```

2020-10-21 20:33 UTC, GrantJamesPowell commented
Glad to help! Super helpful library!

2020-10-22 16:24 UTC, maennchen approved these changes

2020-10-22 16:25 UTC, merged